### ISSUE TITLE
CSS布局

### ISSUE THREAD

**Issue by JameJJ** [JameJJ/Dan_res#4]
## CSS布局

CSS中有块级元素，例如：<div>，还有行内元素，例如<p>。一个块级元素会新开始一行并尽可能撑满容器，行内元素的长度是元素内属性的长度。

```css
#main{
    width: 600px;
    margin: 0 auto;
}
```
设置一个块级元素宽度，防止充满容器，使用margin:auto实现水平居中。

```css
#main{
    max-width: 600px;
    margin: 0 auto;
}
```
将width更改为max-width。可以使浏览器处理更好的小窗口状况。
